name: 'Run an action'
description: 'run action on composite test'

inputs:
  android:
    description: Run KtLint with Android style
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.android }}
  
branding:
  icon: 'edit'
  color: 'blue'
